### ISSUE TITLE
Carbon died?

### ISSUE THREAD

**Issue by prhost** [CarbonDate/Carbon#26]
Carbon original repository died? what happened to it?

**Comment by GawainLynch** [comment]
I've had a short contact with Brian, and basically, he hasn't/hadn't given up on it, he just is super busy with life and work. There is, however, a standing invitation for him to become a co-owner of this GitHub org :smile_cat: 

In one of the projects I maintain, we rely **very** heavily on `Carbon\Carbon` throughout our repos, so we decided to set up a fork and push forward the maintenance so that there is no "one person" responsible. I'm driving the effort right this second, but more maintainers will be publically listed soon.

**Comment by prhost** [comment]
but does not Brian allow someone to continue the work for him while he does not have the time? permission to approve pull requests, many will have to change the composer package 😢

**Comment by GawainLynch** [comment]
Yeah, all still under discussion with him. He's just a very busy person.

Thing is that Brian's 1.22.1 is ultra stable, so as long as you don't need Symfony 4 you can stay with the old Composer package if needed.

For my part, I see this work as "feature complete" for the most part, and there is a PR in the queue that I am working on for PHP 7.1+ support and we'll keep the version 1 branch in supported bug-fix mode for quite a while to come :smile:

**Comment by Ovsyanka** [comment]
Why you decided to make this repo separated from it's parent repository? I mean it is not actually fork - it is just another repository with the same commits.
It is confusing at least for me.

**Comment by GawainLynch** [comment]
Because Brian is hard to reach and I tried over many months … I have had a conversation with him, but no results.

> I mean it is not actually fork - it is just another repository with the same commits.

The same commits are because it *is a fork* and that is the point of a fork. I don't own the code or its history

**Comment by Ovsyanka** [comment]
I didn't ask why is here the same commits =) I know that. My question is why it is not a fork in terms of github? Like https://github.com/Ovsyanka/Carbon for example. We can see that it is fork on the project page:
![default](https://user-images.githubusercontent.com/1226722/34828562-a2510c7a-f6e6-11e7-8bcc-38633e67afed.png)

In your project there is no such connection with the original project. I see you wrote in the README that it is fork, but I dont see the point not making it an "actual" fork.

**Comment by Ovsyanka** [comment]
I don't know where is appropriate place to ask, so I will ask here - did you think about make some chat server for support and discussing? For example it could be Discord or Gitter or something like that.
