### ISSUE TITLE
nesbot/carbon is more updated then carbondate/carbon

### ISSUE THREAD

**Issue by tonybolzan** [CarbonDate/Carbon#28]
nesbot/carbon has version v1.25.0

**Comment by GawainLynch** [comment]
Yes, and this has most of the changes … I just need to sort out where they have done some weird stuff and get tests passing.

**Comment by GawainLynch** [comment]
Also worth noting that the tags here aren't aligned, and a good sum of what was in 1.23 here was not added to Brian's repo until we'll after

**Comment by GawainLynch** [comment]
All synced up now
